version: '2'
services:
  mariadb:
    image: 'docker.io/bitnami/mariadb:10.3-debian-10'
    volumes:
      - './docker/mariadb_data:/bitnami/mariadb'
    environment:
      - MARIADB_ROOT_PASSWORD=XZAKAqwlhou0
      - MARIADB_USER=bn_wordpress
      - MARIADB_PASSWORD=ab19c96cc1
      - MARIADB_DATABASE=bitnami_wordpress
    ports:
      - '3309:3306'
  phpmyadmin:
    image: 'docker.io/bitnami/phpmyadmin:5-debian-10'
    ports:
      - '8080:8080'
      - '4430:8443'
    depends_on:
      - mariadb
  wordpress:
    image: 'docker.io/bitnami/wordpress:5-debian-10'
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      - './docker/wordpress_data/:/bitnami/wordpress/'
      - './:/bitnami/wordpress/wp-content/plugins/wp-olakai-performance-testing-plugin/'
    depends_on:
      - mariadb
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - WORDPRESS_USER=user
      - WORDPRESS_PASSWORD=XZAKAqwlhou0
      - WORDPRESS_EMAIL=contact@olakaiconsulting.com
      - WORDPRESS_BLOG_NAME=Olakai Consulting
      - WORDPRESS_DATABASE_USER=bn_wordpress
      - WORDPRESS_DATABASE_PASSWORD=ab19c96cc1
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local
